apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: stg-rpay-kong
  namespace: rpay-kong
  labels:
    app: stg-rpay-kong
spec:
  securityPolicy:
    name: stg-router-01  
  connectionDraining:
    drainingTimeoutSec: 60
  cdn:
    enabled: false
  logging:
    enable: true
    sampleRate: 1
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 10
    healthyThreshold: 3
    unhealthyThreshold: 1
    type: HTTP
    requestPath: /status
    port: 8100
  timeoutSec: 10

  