apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-server
  template:
    metadata:
      labels:
        app: my-server
    spec:
      containers:
        - name: my-server
          image: asia.gcr.io/r-pay-1/rpay-kong/server-py:1
          ports:
            - containerPort: 18000
